In [1]:
import polars
from xlsxwriter import Workbook

In [2]:
publications = polars.read_database_uri(
    """SELECT id_record, doi, rank_sum
    FROM csml_record
    WHERE rank_sum IS NOT NULL
    ORDER BY rank_sum""",
    "sqlite://sydney.sqlite"
)
publications

shape: (13_459, 3)
┌───────────┬───────────────────────────────┬──────────┐
│ id_record ┆ doi                           ┆ rank_sum │
│ ---       ┆ ---                           ┆ ---      │
│ i64       ┆ str                           ┆ i64      │
╞═══════════╪═══════════════════════════════╪══════════╡
│ 62        ┆ 10.1016/j.jii.2020.100125     ┆ 0        │
│ 70        ┆ 10.1056/NEJMra1906193         ┆ 0        │
│ 85        ┆ 10.1109/TCSI.2020.3036847     ┆ 0        │
│ 138       ┆ 10.1111/nph.18016             ┆ 0        │
│ 152       ┆ 10.1016/j.anr.2019.11.002     ┆ 0        │
│ …         ┆ …                             ┆ …        │
│ 18        ┆ 10.1016/S0140-6736(20)30977-6 ┆ 249998   │
│ 48        ┆ 10.1016/S0140-6736(20)31404-5 ┆ 249998   │
│ 543       ┆ 10.1038/s41591-021-01498-0    ┆ 249998   │
│ 2926      ┆ 10.1093/database/baz085       ┆ 249998   │
│ 50        ┆ 10.1016/S0140-6736(22)01438-6 ┆ 249999   │
└───────────┴───────────────────────────────┴──────────┘

In [5]:
authors = polars.read_database_uri(
    """SELECT reprint AS scopus_id, display_name, COUNT(*) AS publication_count,
        group_concat(distinct qs_subject_area_field_name) as qs_subjects
    FROM csml_record_author a
    JOIN csml_record r ON a.id_record = r.id_record
    WHERE work_external_author_id IS NOT NULL
    GROUP BY reprint
    """,
    "sqlite://sydney.sqlite"
)
authors

shape: (61_179, 4)
┌─────────────┬──────────────────────────────┬───────────────────┬─────────────────────────────────┐
│ scopus_id   ┆ display_name                 ┆ publication_count ┆ qs_subjects                     │
│ ---         ┆ ---                          ┆ ---               ┆ ---                             │
│ str         ┆ str                          ┆ i64               ┆ str                             │
╞═════════════╪══════════════════════════════╪═══════════════════╪═════════════════════════════════╡
│ 10039169500 ┆ Cameron, J.                  ┆ 6                 ┆ Social Sciences & Management,S… │
│ 10039350400 ┆ Hay, J.| Hay, J.F.           ┆ 4                 ┆ Social Sciences & Management,L… │
│ 10039620800 ┆ Johnston, A.                 ┆ 2                 ┆ Engineering & Technology| Life… │
│ 10039827300 ┆ Ukleja, A.                   ┆ 1                 ┆ Natural Sciences                │
│ 10040306800 ┆ Milbau, A.                   ┆ 2                 ┆ Natural Sciences| Life Science… │
│ …           ┆ …                            ┆ …                 ┆ …                               │
│ 9942380500  ┆ Kelsey, C.R.                 ┆ 1                 ┆ Life Sciences & Medicine        │
│ 9942405300  ┆ Horvat, J.C.                 ┆ 4                 ┆ Social Sciences & Management| … │
│ 9942605800  ┆ Wand, T.                     ┆ 2                 ┆ Life Sciences & Medicine        │
│ 9942710000  ┆ Holwerda, B.W.| Holwerda, B. ┆ 19                ┆ Natural Sciences                │
│ 9943675700  ┆ Gerlach, O.                  ┆ 2                 ┆ Life Sciences & Medicine        │
└─────────────┴──────────────────────────────┴───────────────────┴─────────────────────────────────┘

In [6]:
with Workbook("sydney.xlsx") as wb:
    publications.write_excel(wb, "publications", autofit=True)
    authors.write_excel(wb, "authors", autofit=True)